---
apiVersion: v1
data:
  GF_RENDERING_CALLBACK_URL: http://localhost:3000/
  GF_RENDERING_SERVER_URL: http://localhost:8081/render
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: grafana-image-renderer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        envFrom:
        - configMapRef:
            name: grafana-image-renderer
      - name: grafana-image-renderer
        image: grafana/grafana-image-renderer:latest
        env:
        - name: IGNORE_HTTPS_ERRORS
          value: "true"
          
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30004
